FROM langchain/langgraph-api:3.11

ADD . /deps/report-mAIstro

RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*

ARG OPENAI_API_KEY
ARG GOOGLE_API_KEY
ARG ANTHROPIC_API_KEY
ARG TAVILY_API_KEY
ARG REDIS_URI
ARG DATABASE_URI
ARG LANGSMITH_API_KEY

ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY
ENV ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
ENV TAVILY_API_KEY=$TAVILY_API_KEY
ENV REDIS_URI=$REDIS_URI
ENV DATABASE_URI=$DATABASE_URI
ENV LANGSMITH_API_KEY=$LANGSMITH_API_KEY

ENV LANGSERVE_GRAPHS='{"report_masitro": "/deps/report-mAIstro/src/report_maistro/graph.py:graph"}'
ENV PORT=8000

EXPOSE 8000

WORKDIR /deps/report-mAIstro